# Generated by Django 5.0.6 on 2024-12-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algcategory',
            name='slno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='algorithms',
            name='slno',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
