# Generated by Django 5.0.6 on 2024-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0002_alter_algcategory_slno_alter_algorithms_slno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algcategory',
            name='slno',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='algorithms',
            name='slno',
            field=models.AutoField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
