# Generated by Django 5.0.6 on 2024-12-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0003_alter_algcategory_slno_alter_algorithms_slno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithms',
            old_name='slno',
            new_name='catID',
        ),
    ]
