# Generated by Django 5.0.6 on 2024-12-27 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0004_rename_slno_algorithms_catid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algorithms',
            old_name='catID',
            new_name='slno',
        ),
    ]
