# Generated by Django 5.0.6 on 2024-12-27 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0005_rename_catid_algorithms_slno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='algcategory',
            old_name='slno',
            new_name='catID',
        ),
    ]
