# Generated by Django 5.0.6 on 2024-12-27 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algorithms', '0007_alter_algcategory_catid_alter_algorithms_slno'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlgCategory1',
            fields=[
                ('catID', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Algorithms1',
            fields=[
                ('slno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('path', models.CharField(max_length=1000)),
                ('catID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='algorithms.algcategory1')),
            ],
        ),
        migrations.DeleteModel(
            name='AlgCategory',
        ),
        migrations.DeleteModel(
            name='Algorithms',
        ),
    ]
